name: musicapp
description: A Flutter app for learning hymns and psalms.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  just_audio: ^0.9.40
  flutter_pdfview: ^1.3.2
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.4
  audio_service: ^0.18.18
  just_audio_background: ^0.0.1-beta.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/sheets/
    - assets/fonts/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700